### ISSUE TITLE
Doubled bibliography

### ISSUE THREAD

**Issue by tubia** [msprev/panzer#14]
Hi,
I noticed that if you use a child style that use `filter: - run: pandoc-citeproc` and the parent also use the same filter, this is runned two times: in this case it causes the bibliography to be listed two times.

**Comment by msprev** [comment]
That is right. By default, filters of children are run first, before their parents, which are run before those of grandparents, etc. Multiple invocations will be run multiple times. This is because there can be occasions on which one wants a filter to be run more than once (do filter 1, then filter 2, then filter 1 on the results). 

Here are 3 different ways to get the behaviour you want and ensure that repeated invocations of `pandoc-citeproc` don't happen.

First, you could use `kill` or `killall` in the child to empty the runlist. You might add to your child style definition:

```
filter:
    - kill: pandoc-citeproc
    - run: pandoc-citeproc
```

The list is a set of instructions run first to last. The first item tells panzer to kill any previous invocation of `pandoc-citeproc`. The next tells it to run a new instance of `pandoc-citeproc`.

Second option: you could define a separate style (e.g. `AddBib`) that consists only of running the filter `pandoc-citeproc`. Add that style to your document's `style` field (or, third option, add it as a parent to a style definition) any time you want a bibliography:

```
style:
    - MyStyle
    - AddBib
```

or

```
MyStyle:
    parent:
        - AddBib
    ....
```

Let me know if this doesn't solve the problem.

**Comment by tubia** [comment]
Hi @msprev thank you for the explanation. I'll test ASAP and report :)
