### ISSUE TITLE
Allow specifying the output name in the document metadata?

### ISSUE THREAD

**Issue by iandol** [msprev/panzer#28]
Currently Panzer does not allow setting the `output` filename or `to` format in the document metadata. I think I understand the current design. But sometimes it would be nice to run the same Panzer command line and specify the output in the document itself. This is the way some other systems like pandocomatic can be run.

An example usecase is to auto-run panzer on any target folder change...

**Comment by msprev** [comment]
Thanks but I'm not sure I see a use case. 

The `to` and `output` also need to be specified outside the style's metadata because they are used to infer which writer is being used, and hence which metadata settings are used. This seems to me fundamentally the right design too. Look at it this way... I specify in my doc's metadata that I want that doc to be a paper (`style: Paper`). Depending on which writer I then select when I invoke panzer (html, md, latex), different settings are applied from the Paper style's definition to produce the right output (depending on whether I want a paper for the web, print, email.). This seems to me the right way to abstract pandoc's settings -- my document contains one line that determines which type of document it is; the style definition contains all info on how to set pandoc's dials and knobs to produce documents of that style for any output format. It seems the wrong level of abstraction to have a specific writer or specific output filename baked into a style's definition. That isn't a style of document, it's something much more specific to a single document or a single use of a document. Hope this makes sense.

**Comment by iandol** [comment]
@msprev: yes thank you, it certainly makes sense **not** specifying `to` and `output` for the style's metadata. I think that this somehow feels conceptually different for the document metadata to me. The document metadata sits "above" the style metadata, commanding panzer to use a specific style, but what if I always want `to: html5 | output: p.html` for a particular document. The metadata in the document that seems sufficient to define a style is insufficient to define an output, and this gets delegated to the command line. This is nothing major, but if I have a workflow that automatically looks for a document added to a folder, then executes Panzer, how can I specify for docA I want html called "thisA.html" but for docB I want "that.pdf"? 

Thanks so much for an excellent tool!

**Comment by msprev** [comment]
Thank you very much for your kind words. I'm afraid though that this looks like it is departing from the design for panzer a bit too much. It sounds more of a job for a little wrapper script or a makefile...
