### ISSUE TITLE
Pandoc 2.0

### ISSUE THREAD

**Issue by kbro237** [msprev/panzer#31]
Pandoc has been updated to 2.0 status. I'm sure it will take some time to go through all the changes, but right away I notice that the `--smart/-S` option has been deprecated which `panzer` tries to use when making pdf's. I tried to get around it with `no-tex-ligatures` but that's been deprecated, too. The `latex-engine` command line option has also changed to `pdf-engine` which `panzer` is not aware of.

**Comment by msprev** [comment]
Thanks -- yes, I saw the release today. I need to go through the 2.0 release notes carefully and update panzer. I'm planning to release a new version of panzer within a week that supports pandoc 2.0.

**Comment by aalldridge** [comment]
One can call panzer with the option "-t latex+smart" (or similar) to circumvent the issue that -S is deprecated. However, this has the side effect of setting the writer name to "latex+smart". This cause all kinds of issues. For instances, filters get are passed this incorrect writer name as an argument and may then not work properly.

**Comment by msprev** [comment]
I'm not surprised that there will be issues with this. I need to carefully look at the pandoc 2.0 changes to make panzer compatible. Don't worry, I'll do this, but for the moment it's safest to assume pandoc 2.0 will not work.

**Comment by msprev** [comment]
I've updated panzer and it should work with pandoc 2.0 now and bumped the version to 1.3. Let me know if there are any issues. Some things to note:

- panzer now requires pandoc 2.0 or above. It no longer supports older versions of pandoc. If you want to run an older version of pandoc grab version 1.2 of panzer from GitHub (it's very stable).
- I prefer to avoid breaking changes, but since pandoc is introducing the changes itself, it does not make sense for panzer to try to fake pandoc's old command line driven behaviour.
- The new lua filters are not yet supported. I need to think about how to integrate them and see whether there is sufficient demand to support them inside panzer.

**Comment by kbro237** [comment]
Thank you so much for keeping panzer up to date with pandoc. panzer works the way my brain works and I found I couldn't update pandoc until panzer was ready. As long as panzer exists, I am unwilling to use pandoc any other way!

**Comment by msprev** [comment]
Thanks for the kind words! It works well form my brain too. Let me know if there are any issues.
